---
title: "Geospatial-Analysis"
author: "Sean Johnson"
date: "2022-03-24"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries
```{r, warning=FALSE, message=FALSE, include=FALSE}
library(dplyr)
library(mapview) 
library(readr)
library(sf)    
library(tidygeocoder) 
library(tigris)
library(tidyr)
library(tibble)
library(stringr)
```

# Data
```{r, message=FALSE}
travel <- read_csv(here::here("data","travel.csv"))

sales_geo <- read_csv(here::here("data","sales_geocoded.csv"))
```

# EDA
```{r, message=FALSE}
destinations <- travel %>%
    group_by(travelcountry, travellat, travellon) %>%
    summarize(n = n()) %>%
    ungroup() %>%
    arrange(desc(n))

destinations_sf <- destinations %>%
    st_as_sf(
        coords = c("travellon", "travellat"),
        crs    = 4326
    )
```

## View Destination
```{r}
destinations_sf %>%
    mapview(
        cex           = "n",
        col.regions   = Thematic::Cer(n=1),
        alpha.regions = 0.5,
        legend = FALSE
    )
```

## Travel
```{r, message=FALSE}
travel_connections <- travel %>%
    group_by(homelat, homelon, travellat, travellon) %>%
    summarize(n = n()) %>%
    ungroup() %>%
    arrange(desc(n)) %>%
    rowid_to_column()


travel_connections_pl <- travel_connections %>%
    pivot_longer(cols = homelat:travellon) %>%
    mutate(type = ifelse(str_detect(name, "^home"), "home", "travel")) %>%
    mutate(latlon = ifelse(str_detect(name, "lat$"), "lat", "lon")) %>%
    select(-name, -n) %>%
    pivot_wider(
        names_from  = latlon,
        values_from = value
    )


travel_connection_sf <- travel_connections_pl %>%
    st_as_sf(
        coords = c("lon", "lat"),
        crs    = 4326
    )

travel_connection_multipoints_sf <- travel_connection_sf %>%
    group_by(rowid) %>%
    summarise(do.union = FALSE)
```

### Travel Connections
```{r, warning=FALSE}
travel_connection_multipoints_sf %>%
  mapview(
    col.regions   = Thematic::Cer(n=1),
    alpha.regions = 0.5,
    legend = FALSE
    )
```

####  Connections
```{r}
travel_connection_lines_sf <- travel_connection_multipoints_sf %>%
    st_cast("LINESTRING")

travel_connection_lines_sf %>% 
  mapview(
    lwd   = 0.05,
    color = Thematic::Cer(n=1),
    legend = FALSE
    )
```


#### Conections Based on Volume
```{r, message=FALSE}
viz.connections<-travel_connection_lines_sf %>%
    left_join(
        travel_connections %>% 
          select(rowid, n)
    ) %>%
    mapview(
        lwd   = 0.05,
        color = "#B2B5B6",
        legend = FALSE
    ) +
    mapview(
        destinations_sf,
        col.regions   = Thematic::Cer(n=1),
        col           = Thematic::Cer(n=1),
        cex           = "n",
        alpha.regions = 0.1,
        alpha         = 0.1,
        legend = FALSE
    )

viz.connections
```

## Sales/Customer Analysis
```{r, warning=FALSE, message=FALSE}
sales_geo_sf <- sales_geo %>%
    st_as_sf(
        coords = c("lat", "lon"),
        crs    = 4326
    )

sales_geo_sf %>%
    mapview(
      cex = "purchases",
      col.regions = Thematic::Cer(n=1),
      legend = FALSE)
```

```{r, include=FALSE, warning=FALSE, message=FALSE}
ca_counties_sf <- tigris::counties(state = "CA") %>%
    st_set_crs(4326)
```


```{r}
ca_counties_sf %>% 
  mapview(col.regions = "#0197F6",
          col = "black")
```

```{r}
sales_by_county_sf <- sales_geo_sf %>%
  st_join(ca_counties_sf %>%
            select(GEOID)) %>%
    as_tibble() %>%
    group_by(GEOID) %>%
    summarize(
        median_purchases = median(purchases),
        avg_purchases = mean(purchases),
        sum_purchases    = sum(purchases)
    ) %>%
    ungroup() %>%
    right_join(ca_counties_sf, by = "GEOID") %>%
    select(GEOID:sum_purchases, NAME, geometry) %>%
    st_as_sf(crs = 4326)
```

### Average Sales
```{r}
viz.avgSales<-sales_by_county_sf %>%
    mapview(
        zcol       = "avg_purchases",
        color      = "grey",
        map.types  = "CartoDB",
        layer.name = "Average Purchases"
    )

viz.avgSales
```

### Sum of Sales
```{r}
viz.sumSales<-sales_by_county_sf %>%
    mapview(
        zcol       = "sum_purchases",
        color      = "grey",
        map.types  = "CartoDB",
        layer.name = "Sum Purchases"
    )

viz.sumSales
```

## Kmeans Cluster Analysis
```{r}
set.seed(1)
kmeans_obj <- sales_geo_sf %>%
    st_coordinates() %>%
    as_tibble() %>%
    kmeans(centers = 5, nstart = 20)
```

```{r}
viz.salesClusters<-sales_geo_sf %>%
    mutate(cluster = kmeans_obj$cluster %>% factor()) %>%
    mapview(
        zcol       = "cluster",
        cex        = "purchases",
        color      = "grey",
        map.types  = "CartoDB",
        layer.name = "Geospatial Segments"
    )
viz.salesClusters
```


